server:
  port: ${TOMCAT_PORT:8080}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/compasschallenge3_msuser?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
  mvc:
    format:
      date-time: iso
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

mq:
  queues:
    user-queue: ${CHALLENGE3_MQ_USER_QUEUE:user-queue}

security:
  jwt:
    token:
      secret-key: ${CHALLENGE3_JWT_SECRET:909266500255685261705041354583000}
      expire-length: ${CHALLENGE3_JWT_EXPIRATION:3600000}

springdoc:
  swagger-ui:
    path: /docs-msuser.html
  api-docs:
    path: /docs-msuser
  packages-to-scan: com.compassuol.sp.challenge.msuser.web.controller
